#pragma once

// Definitions used within the Graphics Engine

// Reserved Texture Units
#define MESH_OBJECT_COLOUR_TEXTURE_UNIT			0
#define MESH_OBJECT_NORMAL_TEXTURE_UNIT			1
#define DEFERRED_LIGHTS_EMISSIVE_TEXTURE_UNIT	2
#define DEFERRED_LIGHTS_SPECULAR_TEXTURE_UNIT	3
#define GBUFFER_COLOUR_TEXTURE_UNIT				4
#define GBUFFER_NORMALS_TEXTURE_UNIT			5
#define GBUFFER_DEPTH_TEXTURE_UNIT				6
#define SKYBOX_TEXTURE_UNIT						7
#define	GBUFFER_VELOCITY_UNIT	8
#define GBUFFER_COLOUR_TEXTURE_UNIT_1	9
#define GBUFFER_DSAMPLE_TEXTURE_UNIT_0	10
#define GBUFFER_DSAMPLE_TEXTURE_UNIT_1	11
#define GBUFFER_DSAMPLE_TEXTURE_UNIT_2	12
#define SHADOW_TEXTURE_UNIT	13

#define DEFAULT_AMBIENT_LIGHT_COLOUR T3Vector4(0.5f, 0.5f, 0.5f, 1.0f);

#define RENDER_HZ 60
#define SCREEN_WIDTH 1280
#define SCREEN_HEIGHT 720
#define GAME_TITLE "Team^3 - Endless Racer"

// Debug settings
#define DEBUG_DRAW_DEFERRED_LIGHTS 0